### ISSUE TITLE
invalid prop options

### ISSUE THREAD

**Issue by almoraleslopez** [Cemgoktugsorgun/material-ui-geosuggest#1]
Hello.

I've found an issue with material-ui-geosuggest 0.6.0

When using React 15..4.x and MUI 0.17.1 there is a warning message like:
> Warning: Unknown prop `options` on <input> tag

This is caused by the new options props that is passed down to Textfield in ...finalProps

finallProps catch the options props and Textfield doesn't prevent this props to be passed to the input element.

**Comment by Cemgoktugsorgun** [comment]
Hey,

Thanks for pointing out the problem. The warning issue should be resolved with the last commit.
